### ISSUE TITLE
0-byte read in AttrRmtHdr::from

### ISSUE THREAD

**Issue by asomers** [KhaledEmaraDev/xfuse#12]
The latest Clippy detected this bug.  It's a zero-byte read into a Vec, which is almost certainly wrong.  The fix is simple, but I don't know how to test it.  Can you test it, @KhaledEmaraDev ?
```
error: reading zero byte data to `Vec`
   --> src/libxfuse/attr.rs:453:9
    |
453 |         buf_reader.read_exact(&mut data).unwrap();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `data.resize(rm_bytes as usize, 0); buf_reader.read_exact(&mut data).unwrap();`
    |
    = note: `#[deny(clippy::read_zero_byte_vec)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#read_zero_byte_vec
```

**Comment by KhaledEmaraDev** [comment]
Working on it. :+1:

**Comment by asomers** [comment]
@KhaledEmaraDev did you ever look into this?

**Comment by KhaledEmaraDev** [comment]
Hey @asomers, really sorry. I totally forgot about this.

I'm a bit rusty with this but I'll try to figure it out soon and comment back.
