### ISSUE TITLE
Rename the crate

### ISSUE THREAD

**Issue by asomers** [KhaledEmaraDev/xfuse#2]
I just noticed that "xfuse" is already registered on crates.io^ .   So we'll need to rename this project.  The repository can stay the same; just the crate name needs to change.  To fit with convention, it should be something like "*-fuse", where "*" has something to do with XFS.

^ https://crates.io/crates/xfuse

**Comment by KhaledEmaraDev** [comment]
That's a shame. I quite liked this name. Should we change it to `xfs-fuse`?

**Comment by asomers** [comment]
Yeah, I think so.

**Comment by KhaledEmaraDev** [comment]
Done.
